### ISSUE TITLE
Move to the do-core organization

### ISSUE THREAD

**Issue by sameo** [Hasenn/do-core-asm#6]
Hey @Hasenn. Would you be ok moving this repo to the do-core organization?
You'd have full admin access to it, obviously.

**Comment by sameo** [comment]
@Hasenn Let me know if it makes sense to move that repo or not.
And it's perfectly fine if you think it does not :-)

**Comment by Hasenn** [comment]
@sameo Done :D i tried to do that earlier but didn't find how
